#!/usr/bin/env python3
"""
Setup script to populate MongoDB with Utah Teapot data.

This script:
1. Creates or updates credentials.py with MongoDB connection details
2. Connects to MongoDB (local or Atlas)
3. Creates the '3dObjects' database with 'vertices' and 'surfaces' collections
4. Populates collections from CSV files
5. Validates the data

Usage:
    python3 setup_mongodb.py local         # Use local MongoDB (docker)
    python3 setup_mongodb.py atlas         # Use MongoDB Atlas
    python3 setup_mongodb.py               # Prompts for choice
"""

import csv
import os
import sys
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError

# Default config
LOCAL_MONGODB_URI = 'mongodb://localhost:27017/'
DATABASE_NAME = '3dObjects'
VERTICES_COLLECTION = 'vertices'
SURFACES_COLLECTION = 'surfaces'

def create_credentials_file(mongo_type, username=None, password=None):
    """Create or update credentials.py with MongoDB connection details."""
    creds_path = 'credentials.py'

    if mongo_type == 'local':
        content = '''# MongoDB Credentials
# Generated by setup_mongodb.py

MONGODB_ADMIN_USERNAME = "admin"
MONGODB_ADMIN_PASSWORD = "password"

# Note: For local MongoDB, these are not used
# The connection string in server.py uses: mongodb://localhost:27017/
'''
    else:  # atlas
        if not username or not password:
            print("Error: Username and password required for MongoDB Atlas")
            return False
        content = f'''# MongoDB Credentials
# Generated by setup_mongodb.py

MONGODB_ADMIN_USERNAME = "{username}"
MONGODB_ADMIN_PASSWORD = "{password}"

# Atlas connection uses these credentials in server.py:
# mongodb+srv://{{MONGODB_ADMIN_USERNAME}}:{{MONGODB_ADMIN_PASSWORD}}@cluster0.iyzootc.mongodb.net/test
'''

    try:
        with open(creds_path, 'w') as f:
            f.write(content)
        print(f"✓ Created {creds_path}")
        return True
    except IOError as e:
        print(f"✗ Failed to create credentials.py: {e}")
        return False

def connect_to_mongodb(mongo_type, username=None, password=None):
    """Connect to MongoDB (local or Atlas)."""
    if mongo_type == 'local':
        connection_string = LOCAL_MONGODB_URI
        print("Connecting to local MongoDB at localhost:27017...")
    else:  # atlas
        if not username or not password:
            raise ValueError("Username and password required for Atlas")
        connection_string = f'mongodb+srv://{username}:{password}@cluster0.iyzootc.mongodb.net/test'
        print("Connecting to MongoDB Atlas...")

    try:
        client = MongoClient(connection_string, serverSelectionTimeoutMS=5000)
        # Verify connection
        client.admin.command('ping')
        print("✓ Connected successfully")
        return client
    except (ConnectionFailure, ServerSelectionTimeoutError) as e:
        print(f"✗ Connection failed: {e}")
        return None

def load_csv_to_list(filepath):
    """Load CSV file and return list of dictionaries."""
    data = []
    try:
        with open(filepath, 'r', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Convert numeric strings to floats/ints
                processed = {}
                for key, value in row.items():
                    key = key.strip()
                    try:
                        # Try int first (for 'id' column)
                        processed[key] = int(value)
                    except ValueError:
                        try:
                            # Then try float
                            processed[key] = float(value)
                        except ValueError:
                            # Keep as string
                            processed[key] = value
                data.append(processed)
        return data
    except IOError as e:
        print(f"✗ Failed to read {filepath}: {e}")
        return None

def populate_collection(db, collection_name, data, filepath):
    """Populate a MongoDB collection with data from CSV."""
    if not data:
        print(f"✗ No data to load for {collection_name}")
        return False

    try:
        collection = db[collection_name]

        # Drop existing collection
        collection.drop()
        print(f"  Cleared {collection_name} collection")

        # Insert documents
        result = collection.insert_many(data)
        print(f"✓ Inserted {len(result.inserted_ids)} documents into {collection_name}")

        # Validate
        count = collection.count_documents({})
        print(f"  Verified: {count} documents in {collection_name}")

        return True
    except Exception as e:
        print(f"✗ Failed to populate {collection_name}: {e}")
        return False

def validate_data(db):
    """Validate that vertices and surfaces collections are populated correctly."""
    print("\n--- Data Validation ---")

    vertices_col = db[VERTICES_COLLECTION]
    surfaces_col = db[SURFACES_COLLECTION]

    v_count = vertices_col.count_documents({})
    s_count = surfaces_col.count_documents({})

    print(f"Vertices count: {v_count}")
    print(f"Surfaces count: {s_count}")

    if v_count > 0:
        sample_vertex = vertices_col.find_one()
        print(f"Sample vertex: {sample_vertex}")

    if s_count > 0:
        sample_surface = surfaces_col.find_one()
        print(f"Sample surface: {sample_surface}")

    # Check that surfaces reference valid vertex IDs
    if v_count > 0 and s_count > 0:
        max_vertex_id = vertices_col.find_one(sort=[('id', -1)])['id']
        invalid_surfaces = list(surfaces_col.find({
            '$or': [
                {'x': {'$gt': max_vertex_id}},
                {'y': {'$gt': max_vertex_id}},
                {'z': {'$gt': max_vertex_id}}
            ]
        }))

        if invalid_surfaces:
            print(f"⚠ Warning: {len(invalid_surfaces)} surfaces reference non-existent vertices")
        else:
            print("✓ All surface references are valid")

    return v_count > 0 and s_count > 0

def main():
    print("=== MongoDB Setup for PyTracer ===\n")

    # Determine MongoDB type
    if len(sys.argv) > 1:
        mongo_type = sys.argv[1].lower()
        if mongo_type not in ['local', 'atlas']:
            print(f"Invalid type: {mongo_type}")
            print("Usage: python3 setup_mongodb.py [local|atlas]")
            sys.exit(1)
    else:
        print("Choose MongoDB setup:")
        print("1. Local (Docker container)")
        print("2. MongoDB Atlas (cloud)")
        choice = input("Enter choice (1 or 2): ").strip()
        mongo_type = 'local' if choice == '1' else 'atlas'

    print(f"\nSetup type: {mongo_type.upper()}\n")

    # Prompt for Atlas credentials if needed
    username = None
    password = None
    if mongo_type == 'atlas':
        username = input("Enter MongoDB Atlas username: ").strip()
        password = input("Enter MongoDB Atlas password: ").strip()
        if not username or not password:
            print("✗ Username and password are required for Atlas")
            sys.exit(1)

    # Create credentials.py
    print("\n--- Credentials ---")
    if not create_credentials_file(mongo_type, username, password):
        sys.exit(1)

    # Connect to MongoDB
    print("\n--- Connection ---")
    client = connect_to_mongodb(mongo_type, username, password)
    if not client:
        print("\n⚠ Could not connect to MongoDB")
        if mongo_type == 'local':
            print("\nTo run local MongoDB in Docker:")
            print("  docker run --name mongodb -d -p 27017:27017 -v /path/to/data:/data/db mongo")
        sys.exit(1)

    db = client[DATABASE_NAME]

    # Load CSV data
    print("\n--- Loading Data ---")
    vertices_data = load_csv_to_list('objects/utah_teapot_vertices_mdb.csv')
    surfaces_data = load_csv_to_list('objects/utah_teapot_faces_mdb.csv')

    if not vertices_data or not surfaces_data:
        sys.exit(1)

    # Populate collections
    print("\n--- Populating Collections ---")
    v_success = populate_collection(db, VERTICES_COLLECTION, vertices_data, 'objects/utah_teapot_vertices_mdb.csv')
    s_success = populate_collection(db, SURFACES_COLLECTION, surfaces_data, 'objects/utah_teapot_faces_mdb.csv')

    if not (v_success and s_success):
        sys.exit(1)

    # Validate
    if not validate_data(db):
        print("\n⚠ Data validation failed")
        sys.exit(1)

    # Success
    print("\n=== Setup Complete ===")
    print(f"Database: {DATABASE_NAME}")
    print(f"Collections: {VERTICES_COLLECTION}, {SURFACES_COLLECTION}")
    print(f"\nYou can now run:")
    print("  python3 swfvs.py          # Load from file (default)")
    print("  (Set INPUT_DATA_SOURCE = 'db' in swfvs.py to load from MongoDB)")
    print("\nOr start the FastAPI server:")
    print("  uvicorn server:app --reload")
    print("  Then access via: http://localhost:8000/db/3dObjects/vertices/0")

    client.close()

if __name__ == '__main__':
    main()
